/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Sat Feb 10 17:32:02 2018. */

#include "MotorMsg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MotorData_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, MotorData, action, action, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, MotorData, params, action, &DataParam_fields),
    PB_LAST_FIELD
};

const pb_field_t MotorCmd_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, MotorCmd, action, action, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, MotorCmd, params, action, &CmdParam_fields),
    PB_LAST_FIELD
};

const pb_field_t McuWrapper_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, McuWrapper, uuid, uuid, 0),
    PB_ONEOF_FIELD(content,   2, MESSAGE , ONEOF, STATIC  , OTHER, McuWrapper, motorData, uuid, &MotorData_fields),
    PB_ONEOF_FIELD(content,   3, MESSAGE , ONEOF, STATIC  , UNION, McuWrapper, motorCmd, uuid, &MotorCmd_fields),
    PB_LAST_FIELD
};

const pb_field_t DataParam_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, DataParam, id, id, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, DataParam, value, id, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, DataParam, unit, value, 0),
    PB_LAST_FIELD
};

const pb_field_t CmdParam_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, CmdParam, id, id, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, CmdParam, value, id, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, CmdParam, unit, value, 0),
    PB_LAST_FIELD
};







/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(McuWrapper, content.motorData) < 65536 && pb_membersize(McuWrapper, content.motorCmd) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MotorData_MotorCmd_McuWrapper_DataParam_CmdParam)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(McuWrapper, content.motorData) < 256 && pb_membersize(McuWrapper, content.motorCmd) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MotorData_MotorCmd_McuWrapper_DataParam_CmdParam)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
