/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Sat May 26 22:38:57 2018. */

#include "MotorMsg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t McuWrapper_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, McuWrapper, uuid, uuid, 0),
    PB_ONEOF_FIELD(content,   2, MESSAGE , ONEOF, STATIC  , OTHER, McuWrapper, motor_data, uuid, &McuWrapper_MotorData_fields),
    PB_ONEOF_FIELD(content,   3, MESSAGE , ONEOF, STATIC  , UNION, McuWrapper, motor_cmd, uuid, &McuWrapper_MotorCmd_fields),
    PB_LAST_FIELD
};

const pb_field_t McuWrapper_MotorData_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, McuWrapper_MotorData, action, action, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, McuWrapper_MotorData, params, action, &McuWrapper_MotorData_DataParam_fields),
    PB_LAST_FIELD
};

const pb_field_t McuWrapper_MotorData_DataParam_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, McuWrapper_MotorData_DataParam, id, id, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, McuWrapper_MotorData_DataParam, value, id, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, McuWrapper_MotorData_DataParam, unit, value, 0),
    PB_LAST_FIELD
};

const pb_field_t McuWrapper_MotorCmd_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, McuWrapper_MotorCmd, action, action, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, McuWrapper_MotorCmd, params, action, &McuWrapper_MotorCmd_CmdParam_fields),
    PB_LAST_FIELD
};

const pb_field_t McuWrapper_MotorCmd_CmdParam_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, McuWrapper_MotorCmd_CmdParam, id, id, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, McuWrapper_MotorCmd_CmdParam, value, id, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, McuWrapper_MotorCmd_CmdParam, unit, value, 0),
    PB_LAST_FIELD
};







/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(McuWrapper, content.motor_data) < 65536 && pb_membersize(McuWrapper, content.motor_cmd) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_McuWrapper_McuWrapper_MotorData_McuWrapper_MotorData_DataParam_McuWrapper_MotorCmd_McuWrapper_MotorCmd_CmdParam)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(McuWrapper, content.motor_data) < 256 && pb_membersize(McuWrapper, content.motor_cmd) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_McuWrapper_McuWrapper_MotorData_McuWrapper_MotorData_DataParam_McuWrapper_MotorCmd_McuWrapper_MotorCmd_CmdParam)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
