/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.Orbit');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Orbit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Orbit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Orbit.displayName = 'proto.Orbit';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Orbit.prototype.toObject = function(opt_includeInstance) {
  return proto.Orbit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Orbit} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Orbit.toObject = function(includeInstance, msg) {
  var f, obj = {
    velocity: msg.getVelocity(),
    direction: msg.getDirection(),
    acceleration: msg.getAcceleration(),
    degrees: msg.getDegrees()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Orbit} The clone.
 */
proto.Orbit.prototype.cloneMessage = function() {
  return /** @type {!proto.Orbit} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional double velocity = 1;
 * @return {number}
 */
proto.Orbit.prototype.getVelocity = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.Orbit.prototype.setVelocity = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string direction = 2;
 * @return {string}
 */
proto.Orbit.prototype.getDirection = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.Orbit.prototype.setDirection = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional double acceleration = 3;
 * @return {number}
 */
proto.Orbit.prototype.getAcceleration = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.Orbit.prototype.setAcceleration = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional double degrees = 4;
 * @return {number}
 */
proto.Orbit.prototype.getDegrees = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.Orbit.prototype.setDegrees = function(value) {
  jspb.Message.setField(this, 4, value);
};


