version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx1024m
      TERM: dumb
    
    steps:
      - checkout
      - run: gradle jar
      
  publish:     
    docker:
      - image: circleci/node:8.11.3
      - image: circleci/golang:1.10.2

    environment:
        project_name: 'addrobots_proto'
          
    steps:
      - checkout
      
      - run: sudo npm install github-release-notes -g
      - run: git config user.name $CIRCLE_PROJECT_USERNAME
      - run: github-release upload --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME --tag $CIRCLE_TAG --name $CIRCLE_PROJECT_REPONAME"."$CIRCLE_TAG"-build-"$CIRCLE_BUILD_NUM".jar" --file build/libs/addrobots_proto.jar

      - run: sudo go get github.com/aktau/github-release
      - run: git config user.name $CIRCLE_PROJECT_USERNAME
      - run: github-release upload --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME --tag $CIRCLE_TAG --name $CIRCLE_PROJECT_REPONAME"."$CIRCLE_TAG"-build-"$CIRCLE_BUILD_NUM".jar" --file build/libs/addrobots_proto.jar
          
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build