version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx1024m
      TERM: dumb
    
    steps:
      - checkout
      - run: gradle jar
      
      - persist_to_workspace:
          root: build
          paths:
            - libs
      
  publish_artifacts:     
    docker:
      - image: circleci/golang:1.10.2

    environment:
        project_name: 'addrobots_proto'
          
    steps:
      - attach_workspace:
          at: /tmp/workspace
        
      - checkout
      - run: git config user.name $CIRCLE_PROJECT_USERNAME 
      - run: go get github.com/aktau/github-release
      - run: github-release upload --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME --name "$CIRCLE_PROJECT_REPONAME"-build-"$CIRCLE_BUILD_NUM".jar --file /tmp/workspace/addrobots_proto.jar
          
  publish_notes:     
    docker:
      - image: circleci/node:8.11.3

    environment:
        project_name: 'addrobots_proto'
          
    steps:
      - checkout
      - run: git config user.name $CIRCLE_PROJECT_USERNAME
      - run: sudo npm install github-release-notes -g
      - run: gren release --token="$GITHUB_TOKEN"
           
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish_artifacts:
          requires:
            - build
      - publish_notes:
          requires:
            - build